openapi: 3.0.0
servers:
  - url: https://devquotesapi.flightcommand.com/quoting/v1
  - url: http://localhost:3000/v1
info:
  version: "1.0.0"
  title: Quoting API
  description: Flight command quoting API
security:
  - Authorization: []

paths:
  # Closest airports
  /airports/closest:
    $ref: ./paths/airports-closest.yaml
  # Calculate flighttime between airport
  /airports/flightTime:
    $ref: ./paths/airports-flighttime.yaml
  /tails:
    $ref: ./paths/tails.yaml
  /trips/prepareTrip:
    $ref: ./paths/trips-pricing.yaml
  /rfqs/summary:
    $ref: ./paths/rfqs-summary.yaml
  /rfqs:
    $ref: ./paths/rfqs.yaml
  /rfqs/sent:
    $ref: ./paths/rfqs-sent.yaml
  /rfqs/received:
    $ref: ./paths/rfqs-received.yaml
  /rfqs/{rfqId}:
    $ref: ./paths/rfqs-id.yaml
  /rfqs/{rfqId}/quotes:
    $ref: ./paths/rfqs-id-quotes.yaml
  /quotes/{quoteId}:
    $ref: ./paths/quotes-id.yaml
  /quotes/{quoteId}/confirmation:
    $ref: ./paths/quotes-id-confirmation.yaml
  /quotes/envelopes/{envelopeId}/signing:
    $ref: ./paths/envelopes-id-signing.yaml
  /quotes/envelopes/{envelopeId}/embeddedLink:
    $ref: ./paths/envelopes-id-embeddedlink.yaml

components:
  schemas: {}
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      bearerFormat: JWT
